/* SANDBAGGED — GUARD-9: the negative tests, kept.
 *
 * `test.mjs` opens by saying that fifteen one-off harnesses were written across this
 * project, each proving something real, and every one of them was thrown away — and that
 * this is why the kept suite exists. The injections are the same story one level up.
 *
 * Every ticket here has been negative-tested: break the thing the guard claims and check
 * the guard says so. That is the only way to know a guard can fail at all, and in this
 * project it has repeatedly been the only way to find out that one CANNOT. Across
 * GUARD-8, CARD-18, SKIRM-7, SIM-7 and SIM-8 the injections found the original bug every
 * time AND three VACUOUS ASSERTIONS in guards written minutes earlier:
 *
 *   SKIRM-7 — asserted `partnerFor(st)` appeared in the screen. It does, into a local,
 *             even when the block that renders it is gated off.
 *   SIM-7  — asserted a send rate that cannot see the bug and points the other way: the
 *             illegal deck sends 99% of one boulder and completes 18.9% of campaigns.
 *   SIM-8  — asserted beta cards were absent from a list the TEST had just built, rather
 *             than from the one the harness uses.
 *
 * Every one of those read green. GUARD-8 made a fragile source WINDOW impossible; this is
 * the other shape — an assertion that tests the fixture instead of the claim — and nothing
 * static catches it. Running it does.
 *
 * So the injections stop being scratch files:
 *
 *   node sim/mutants.mjs          the fast set (the core and kept suites)
 *   node sim/mutants.mjs slow     also the ones that need the balance ledger
 *   node sim/mutants.mjs GUARD-8  just one ticket's
 *
 * It EDITS SOURCE FILES and puts them back. Every file it touches is snapshotted first,
 * restored after each mutant, restored again on any crash or Ctrl-C, and byte-compared at
 * exit — if that comparison ever fails it says so loudly rather than leaving you with a
 * mutated tree.
 *
 * A cheap part of this runs inside `test-core.mjs` on every `npm run check` (GUARD-9's own
 * guard): every mutant's ANCHOR must still match its file exactly once. That is the way a
 * kept injection rots without anybody noticing — somebody edits the line it patches, the
 * anchor stops matching, and the mutant quietly tests nothing. It is the same failure mode
 * as the guards it protects, so it gets the same treatment.
 *
 * The other rot — the `catches` message drifting away from what the guard actually prints —
 * CANNOT be checked cheaply, and it is worth saying why rather than pretending. Most of
 * these messages are template literals, so `card of 248 carries restChip` is not a string
 * that exists anywhere in the source; it only exists once a failing run has built it. So
 * that half is caught by RUNNING this, and it caught three of them while GUARD-9 was being
 * written: two `catches` strings a word out, and one that still named an assertion I had
 * reworded ten minutes earlier.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'

/* Each mutant: the ticket it belongs to, the patch (one or more exact string swaps that
   must each match exactly once), which suite should notice, and a fragment of the failure
   message that must appear. `catches` is the important field — a mutant that merely makes
   SOMETHING fail proves nothing about the guard you meant to test. */
export const MUTANTS = [
  // ---- GUARD-8: the suite reads itself ------------------------------------------
  { id: 'GUARD-8/fixed-window', suite: 'core',
    why: 'a window with a hard-coded length', catches: 'a window with a hard-coded length',
    patch: [['sim/test-core.mjs',
      "  const pa = region(eng, 'export function powerAgainst', ['export function biteAgainst'],\n    { min: 400, what: 'powerAgainst' })",
      "  const pa = eng.slice(eng.indexOf('export function powerAgainst') + 0, eng.indexOf('export function powerAgainst') + 400)"]] },
  { id: 'GUARD-8/unchecked-anchor', suite: 'core',
    why: 'a window taken straight off indexOf, in the OTHER suite file', catches: 'straight off indexOf',
    patch: [['sim/test.mjs',
      '  const more = tail(app, "st.phase === \'more\'", { min: 500, what: \'the more screen\' })',
      '  const more = app.slice(app.indexOf("st.phase === \'more\'"))']] },
  { id: 'GUARD-8/two-line-anchor', suite: 'core',
    why: 'a variable set from indexOf and sliced later', catches: 'which this file sets from an indexOf',
    patch: [['sim/test-core.mjs',
      "  const marks = region(app, 'const NODE_MARK', ['}'], { min: 60, what: 'the mark vocabulary' })",
      "  const markAt = app.indexOf('const NODE_MARK')\n  const marks = app.slice(markAt, 9999)"]] },
  { id: 'GUARD-8/no-message', suite: 'core',
    why: 'an assertion with no failure message', catches: 'no failure message',
    patch: [['sim/test-core.mjs',
      "  ok(/load\\(st\\.slot\\)/.test(imp), 'IMPORT still does not reload, so the import gets overwritten')",
      '  ok(/load\\(st\\.slot\\)/.test(imp))']] },
  { id: 'GUARD-8/ok-accepts-no-message', suite: 'core',
    why: 'ok() stops demanding a message', catches: 'accepts an assertion with no failure message',
    patch: [['sim/guard.mjs',
      "  if (!m) throw new Error('GUARD-8: this assertion has no failure message, so its failure says nothing')\n  if (!c) throw new Error(m)",
      '  if (!c) throw new Error(m)']] },
  { id: 'GUARD-8/region-size', suite: 'core',
    why: 'region stops checking its own size', catches: 'region does not check its own size',
    patch: [['sim/guard.mjs', '  if (out.length < min) {', '  if (false) {']] },
  { id: 'GUARD-8/region-eof', suite: 'core',
    why: 'region silently reads to the end of the file', catches: 'closing anchor is gone',
    patch: [['sim/guard.mjs', '  if (bounds.length && !found && !eof) {', '  if (false) {']] },
  { id: 'GUARD-8/region-open-anchor', suite: 'core',
    why: 'region stops checking its opening anchor', catches: 'the opening anchor is gone',
    patch: [['sim/guard.mjs',
      '  if (at < 0) throw new Error(`${name}: the opening anchor is gone',
      '  if (false) throw new Error(`${name}: the opening anchor is gone']] },

  // ---- CARD-18: four mechanics you would never meet twice -----------------------
  { id: 'CARD-18/back-to-singleton', suite: 'core',
    why: 'a mechanic back to one card', catches: 'card of 248 carries restChip',
    patch: [['src/engine.ts',
      "  rest('Milk The Jug', 6, 3, 'uncommon', { restChip: 1, anchor: false,",
      "  rest('ZGone The Jug', 6, 3, 'uncommon', { anchor: false,"]] },
  { id: 'CARD-18/free-chip', suite: 'core',
    why: 'the chip becomes free — a strict upgrade on Shake Out', catches: 'the chip has to cost something',
    patch: [['src/engine.ts',
      "rest('Milk The Jug', 6, 3, 'uncommon', { restChip: 1, anchor: false,",
      "rest('Milk The Jug', 6, 3, 'uncommon', { restChip: 1,"]] },
  { id: 'CARD-18/free-latch', suite: 'core',
    why: 'the latch becomes free — a strict upgrade on Precise Feet', catches: 'a common plus a free latch',
    patch: [['src/engine.ts',
      "ft('Rand Smear', 1, 6, 'uncommon', { support: 2, latch: true,",
      "ft('Rand Smear', 1, 7, 'uncommon', { support: 2, latch: true,"]] },
  { id: 'CARD-18/read-strict-upgrade', suite: 'core',
    why: 'the deeper read also draws', catches: 'so it is a strict upgrade',
    patch: [['src/engine.ts',
      "bn('Take It All In', 1, 'uncommon', { read: 4,",
      "bn('Take It All In', 1, 'uncommon', { read: 4, draw: 1,"]] },
  { id: 'CARD-18/spawn-drops-field', suite: 'core',
    why: 'spawn drops restChip again — the CARD-11 bug that shipped a dead card',
    catches: 'spawn dropped restChip',
    patch: [['src/engine.ts',
      '    restChip: d.restChip, hex: d.hex,   // CARD-11 / CARD-13: were dropped here, so both were dead in play',
      '    hex: d.hex,   // CARD-11 / CARD-13']] },
  { id: 'CARD-18/chip-wrong-lane', suite: 'core',
    why: 'the chip leaks into a lane you did not rest in', catches: 'chipped a lane it was not resting in',
    patch: [['src/engine.ts',
      '    if (c && c.restChip && h) boardH[i] = { ...h, grip: Math.max(0, h.grip - c.restChip) }',
      '    const cc = boardP.find(x => x && x.restChip); if (cc && h) boardH[i] = { ...h, grip: Math.max(0, h.grip - cc.restChip) }']] },
  { id: 'CARD-18/latch-forever', suite: 'core',
    why: 'the latch stops being once-only', catches: 'the latch is not marked',
    patch: [['src/engine.ts',
      '        boardP[i] = { ...card, contact: 1, latched: true }',
      '        boardP[i] = { ...card, contact: 1 }']] },
  { id: 'CARD-18/into-rewards', suite: 'core',
    why: 'a new card slips into the in-run reward pool — a silent band change',
    catches: 'that is a band change, measure it',
    patch: [['src/engine.ts',
      "  uncommon: ['Cross-Through', 'Lock & Bump', 'Dyno', 'Toe Hook', 'Visualize', 'Try-Hard Scream',",
      "  uncommon: ['Milk The Jug', 'Cross-Through', 'Lock & Bump', 'Dyno', 'Toe Hook', 'Visualize', 'Try-Hard Scream',"]] },
  { id: 'CARD-18/drafter-blind-to-chip', suite: 'core',
    why: 'the drafter goes blind to restChip again', catches: 'the same with and without its chip',
    patch: [['src/engine.ts', '  if (c.restChip) v += c.restChip * 3', '  if (false) v += c.restChip * 3']] },
  { id: 'CARD-18/read-becomes-power', suite: 'core',
    why: 'reading ahead starts changing the turn — information becomes a power',
    catches: 'reading is a power now',
    patch: [['src/engine.ts',
      '  out = { ...out, pump, flow, readAhead: flowRead, turn: s.turn + 1,',
      '  out = { ...out, pump: Math.max(0, pump - (s.readAhead > 0 ? 1 : 0)), flow, readAhead: flowRead, turn: s.turn + 1,']] },
  { id: 'CARD-18/keyword-says-nothing', suite: 'core',
    why: 'a keyword stops saying what it does', catches: 'skin is unexplained',
    patch: [['src/engine.ts',
      "  { name: 'Skin', text: 'How much more your hands will take on this trip. Falls cost it, a camp gives some back,",
      "  { name: 'Skin', text: 'How much more your hands will take on this trip. Some cards spend it. Some cards spend it,"]] },

  // ---- SKIRM-7: the Circuit had nobody in it ------------------------------------
  { id: 'SKIRM-7/circuit-alone', suite: 'core',
    why: 'THE BUG: the partner gate back to inRun only', catches: 'the Circuit still goes out alone',
    patch: [['src/engine.ts', "  if (!s.inRun && !s.circuit && s.result !== 'walked') return null",
      "  if (!s.inRun && s.result !== 'walked') return null"]] },
  { id: 'SKIRM-7/gate-too-wide', suite: 'core',
    why: 'the gate widened so every mode gets a partner',
    catches: 'so the gate widened further than the Circuit',
    patch: [['src/engine.ts', "  if (!s.inRun && !s.circuit && s.result !== 'walked') return null",
      '  if (false) return null']] },
  { id: 'SKIRM-7/partner-changes', suite: 'core',
    why: 'the partner changes as the circuit goes deeper', catches: 'the partner changed at line',
    patch: [['src/engine.ts',
      '  return PARTNERS[(s.runSeed >>> 0) % PARTNERS.length]\n}\n/** SKIRM-7: whether they would go again',
      '  return PARTNERS[((s.runSeed >>> 0) + (s.circuitScore || 0)) % PARTNERS.length]\n}\n/** SKIRM-7: whether they would go again']] },
  { id: 'SKIRM-7/one-shared-threshold', suite: 'core',
    why: 'the threshold stops being theirs', catches: 'said they would',
    patch: [['src/engine.ts',
      "  return s.circuitScore >= p.enough ? 'enough' : 'again'",
      "  return s.circuitScore >= 6 ? 'enough' : 'again'"]] },
  { id: 'SKIRM-7/no-disagreement', suite: 'core',
    why: 'the partners all stop at the same point', catches: 'does not matter',
    patch: [['src/engine.ts',
      "    enough: 10,\n    says: {\n      again: 'She is already pulling the rope through.",
      "    enough: 14,\n    says: {\n      again: 'She is already pulling the rope through."],
      ['src/engine.ts',
      '    enough: 6,\n    says: {\n      again: \'"Go on then, while it is cool."',
      '    enough: 14,\n    says: {\n      again: \'"Go on then, while it is cool."'],
      ['src/engine.ts',
      '    enough: 3,\n    says: {\n      again: \'"If you must."',
      '    enough: 14,\n    says: {\n      again: \'"If you must."']] },
  { id: 'SKIRM-7/circuit-silent', suite: 'core',
    why: 'the ambience bed goes silent for the Circuit again', catches: 'the Circuit climbs in silence again',
    patch: [['src/engine.ts',
      '    if (s.circuit) return circuitBed(s.circuitScore)',
      '    if (false) return circuitBed(s.circuitScore)']] },
  { id: 'SKIRM-7/bed-flat', suite: 'core',
    why: 'the bed stops changing with depth', catches: 'carries no information',
    patch: [['src/engine.ts',
      "export const CIRCUIT_BEDS: Record<number, Bed> = { 0: 'forest', 3: 'forest', 6: 'desert', 10: 'alpine', 14: 'alpine' }",
      "export const CIRCUIT_BEDS: Record<number, Bed> = { 0: 'forest', 3: 'forest', 6: 'forest', 10: 'forest', 14: 'forest' }"]] },
  { id: 'SKIRM-7/zone-with-no-bed', suite: 'core',
    why: 'a new zone with no bed of its own', catches: 'has no bed of its own',
    patch: [['src/engine.ts',
      "  if (n >= 14) return { name: 'Into the Dark',",
      "  if (n >= 20) return { name: 'The Deep', text: 'Deeper than anyone has been.', floor: 20 }\n  if (n >= 14) return { name: 'Into the Dark',"]] },
  { id: 'SKIRM-7/daily-gets-a-bed', suite: 'core',
    why: 'the deliberate exceptions break — a daily picks up a bed',
    catches: 'picked up an ambience bed it is meant not to have',
    patch: [['src/engine.ts',
      "    if (s.circuit) return circuitBed(s.circuitScore)\n    return 'none'",
      "    return circuitBed(s.circuitScore)\n    return 'none'"]] },
  { id: 'SKIRM-7/partner-not-rendered', suite: 'core',
    why: 'the partner is in the data but not on the screen', catches: 'nobody is standing there between lines',
    patch: [['src/App.tsx',
      '        {mate ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--tan)\' }}>',
      '        {false && mate ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--tan)\' }}>']] },
  { id: 'SKIRM-7/opinion-unmarked', suite: 'core',
    why: 'their view stops being marked on the buttons', catches: 'so it is flavour rather than an opinion',
    patch: [['src/App.tsx',
      "        {mate && push === 'again' ? (\n          <div className=\"sub\" style={{ color: 'var(--tan)', marginTop: 3 }}>\n            ▸ {mate.name} would go again.</div>) : null}",
      '        {null}']] },
  { id: 'SKIRM-7/season-carve-out', suite: 'core',
    why: 'the season carve-out is quietly reversed', catches: 'that is farmable',
    patch: [['src/engine.ts',
      '    seasonId: sk, seasonScore, seasonDays, seasonWeeks: wks,',
      '    seasonId: sk, seasonScore: seasonScore + s.circuitScore, seasonDays, seasonWeeks: wks,']] },
  { id: 'SKIRM-7/mechanical-partner', suite: 'core',
    why: 'a partner field that does not just select text',
    catches: 'carries a field a partner should not have',
    patch: [['src/engine.ts', '    enough: 10,\n    says: {', '    enough: 10, dPower: 2,\n    says: {']] },

  // ---- SIM-7: BUILD ME ONE was handing you an illegal deck -----------------------
  { id: 'SIM-7/rare-slots-off', suite: 'kept',
    why: 'THE BUG: the builder stops counting its rares', catches: 'rares against a limit of',
    patch: [['src/engine.ts',
      "      if (r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue",
      "      if (false && r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue"]] },
  { id: 'SIM-7/uncommon-slots-off', suite: 'kept',
    why: 'the uncommon slot rule removed', catches: 'uncommons against a limit of',
    patch: [['src/engine.ts',
      "      if (r === 'uncommon' && slotsUsed(deck, 'uncommon') >= UNCOMMON_SLOTS) continue",
      "      if (false && r === 'uncommon' && slotsUsed(deck, 'uncommon') >= UNCOMMON_SLOTS) continue"]] },
  { id: 'SIM-7/bad-seed-topped-up', suite: 'kept',
    why: 'a loadout already over the limit gets topped up (>= slipped to ===)',
    catches: 'already over the limit',
    patch: [['src/engine.ts',
      "      if (r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue",
      "      if (r === 'rare' && slotsUsed(deck, 'rare') === RARE_SLOTS) continue"]] },
  { id: 'SIM-7/beta-into-decks', suite: 'kept',
    why: 'buildable stops refusing beta cards', catches: 'put them in the deck the game builds',
    patch: [['src/engine.ts',
      "  return [...starter, ...owned.filter(n => CARDS[n] && CARDS[n].rarity !== 'curse'\n    && CARDS[n].rarity !== 'beta' && CARDS[n].rarity !== 'starter')]",
      "  return [...starter, ...owned.filter(n => CARDS[n] && CARDS[n].rarity !== 'curse'\n    && CARDS[n].rarity !== 'starter')]"]] },
  { id: 'SIM-7/picker-drifts', suite: 'kept',
    why: 'the card picker and the builder stop reading the same rule', catches: 'have drifted',
    patch: [['src/App.tsx',
      "      if (r === 'rare' && slotsUsed(cur, 'rare') >= RARE_SLOTS) return s",
      "      if (r === 'rare' && slotsUsed(cur, 'rare') >= 99) return s"],
      ['src/App.tsx',
      "      if (r === 'uncommon' && slotsUsed(cur, 'uncommon') >= UNCOMMON_SLOTS) return s",
      "      if (r === 'uncommon' && slotsUsed(cur, 'uncommon') >= 99) return s"],
      ['src/App.tsx',
      "          rare {slotsUsed(mine, 'rare')}/{RARE_SLOTS} · uncommon {slotsUsed(mine, 'uncommon')}/{UNCOMMON_SLOTS}",
      "          rare {slotsUsed(mine, 'rare')} · uncommon {slotsUsed(mine, 'uncommon')}"],
      ['src/App.tsx',
      "                  || (c.rarity === 'rare' && slotsUsed(mine, 'rare') >= RARE_SLOTS)\n                  || (c.rarity === 'uncommon' && slotsUsed(mine, 'uncommon') >= UNCOMMON_SLOTS)",
      "                  || (c.rarity === 'rare' && slotsUsed(mine, 'rare') >= 99)\n                  || (c.rarity === 'uncommon' && slotsUsed(mine, 'uncommon') >= 99)"],
      ['src/App.tsx',
      '  PUMP_MAX, Phase, RARE_SLOTS, RNG, ROCK, ROUTES, RUN_SKIN, Rarity, SKIN_MAX,',
      '  PUMP_MAX, Phase, RNG, ROCK, ROUTES, RUN_SKIN, Rarity, SKIN_MAX,'],
      ['src/App.tsx',
      '  UNCOMMON_SLOTS, WEATHER, abilityOf, activeSlot, aheadSummary, applyOutcome,',
      '  WEATHER, abilityOf, activeSlot, aheadSummary, applyOutcome,']] },
  { id: 'SIM-7/rare-stuffed-legal', suite: 'kept',
    why: 'the slot limits raised so the original rare-stuffed deck is legal again',
    catches: 'already over the limit',
    patch: [['src/engine.ts', 'export const RARE_SLOTS = 1', 'export const RARE_SLOTS = 10'],
      ['src/engine.ts', 'export const UNCOMMON_SLOTS = 3', 'export const UNCOMMON_SLOTS = 10']] },
  { id: 'SIM-7/measured-floor', suite: 'slow',
    why: 'the measured floor under the deck the game builds',
    catches: 'it is offering to make you worse',
    patch: [['src/engine.ts',
      "      if (r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue",
      "      if (false && r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue"]] },

  // ---- SIM-8: the band measures a deck a player can hold ------------------------
  { id: 'SIM-8/harness-builds-its-own', suite: 'core',
    why: 'THE BUG: the harness builds its own deck again', catches: 'instead of asking the engine',
    patch: [['sim/run.mjs',
      '  return E.buildLoadout(st, [], owned)',
      "  return Object.keys(E.CARDS).filter(n => E.CARDS[n].rarity !== 'curse').slice(0, 15)"]] },
  { id: 'SIM-8/second-opinion', suite: 'core',
    why: 'the harness grows a second card-scoring opinion inside the builder',
    catches: 'scoring cards by hand again',
    patch: [['sim/run.mjs',
      '  return E.buildLoadout(st, [], owned)',
      '  const pick = owned.sort((a, b) => E.CARDS[b].power - E.CARDS[a].power)\n  return E.buildLoadout(st, pick.slice(0, 2), owned)']] },
  { id: 'SIM-8/beta-claimed-as-owned', suite: 'core',
    why: 'the harness stops restricting itself to the collectible rarities',
    catches: 'restricts itself to the collectible rarities',
    patch: [['sim/run.mjs',
      "    .filter(n => ['common', 'uncommon', 'rare'].includes(E.CARDS[n].rarity ?? 'common'))",
      "    .filter(n => E.CARDS[n].rarity !== 'curse')"]] },
  { id: 'SIM-8/buildable-lets-beta-through', suite: 'core',
    why: 'buildable stops refusing beta, so claiming them puts them back in the measured deck',
    catches: 'puts them back in the measured deck',
    patch: [['src/engine.ts',
      "  return [...starter, ...owned.filter(n => CARDS[n] && CARDS[n].rarity !== 'curse'\n    && CARDS[n].rarity !== 'beta' && CARDS[n].rarity !== 'starter')]",
      "  return [...starter, ...owned.filter(n => CARDS[n] && CARDS[n].rarity !== 'curse'\n    && CARDS[n].rarity !== 'starter')]"]] },
  { id: 'SIM-8/measured-deck-illegal', suite: 'core',
    why: 'the measured deck goes illegal', catches: 'rares against',
    patch: [['src/engine.ts',
      "      if (r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue",
      "      if (false && r === 'rare' && slotsUsed(deck, 'rare') >= RARE_SLOTS) continue"]] },
  { id: 'SIM-8/band-excludes-its-pin', suite: 'core',
    why: 'the pin number and its band drift apart', catches: 'but its band is',
    patch: [['sim/test.mjs', '    ok(full > 38 && full < 50,', '    ok(full > 60 && full < 80,']] },
  { id: 'SIM-8/band-too-wide', suite: 'core',
    why: 'the band widened until it could not catch a drift',
    catches: 'which would not catch a BAL-14 slide',
    patch: [['sim/test.mjs', '    ok(full > 38 && full < 50,', '    ok(full > 5 && full < 95,']] },
  { id: 'SIM-8/repin-undated', suite: 'core',
    why: 'the re-pin loses its date', catches: 'does not say which version set the pin',
    patch: [['sim/test.mjs',
      '    /* THE PIN IS ~44, RE-SET AT v10.23 (SIM-8), and this is a deliberate dated re-pin in',
      '    /* THE PIN IS ~44, and this is a deliberate dated re-pin in'],
      ['sim/test.mjs',
      '      `the campaign completes ${full}% with a full journal — ~44, re-pinned at v10.23 (SIM-8)`)',
      '      `the campaign completes ${full}% with a full journal — ~44, re-pinned lately`)']] },

  // ---- GUARD-9: the kept injections themselves ----------------------------------
  /* A ticket that says every guard gets injections had better have its own. These are
     safe from recursion because the runner loads its table into memory before it patches
     anything, so a mutated table only affects the suite it then runs.
     Note the SPLIT STRINGS below. A mutant that patches this file has to quote the line it
     targets, which puts a second verbatim copy in the file and makes its own anchor match
     twice — so the anchor check kills it, correctly. Writing the needle in two halves means
     the file never holds a whole second copy. It is the same self-reference GUARD-8 needed
     its `guard-8: allow` marker for, and it wants the same kind of note rather than a
     silently clever line. */
  { id: 'GUARD-9/dead-anchor', suite: 'core',
    why: 'a kept injection whose anchor has moved, so it patches nothing',
    catches: 'patch nothing any more',
    /* by REFORMATTING the line a mutant targets — behaviour identical, anchor dead. That is
       how this actually happens: nobody deletes an anchor on purpose. */
    patch: [['sim/guard.mjs', '  if (out.length < min) {', '  if (out.length  < min) {']] },
  { id: 'GUARD-9/injection-expects-nothing', suite: 'core',
    why: 'an injection that does not say which guard it expects to hear from',
    catches: 'does not say what it expects to hear',
    patch: [['sim/mutants.mjs',
      "    why: 'region stops checking its own size', catches: 'region does not check its own siz" + "e',",
      "    why: 'region stops checking its own size', catches: '',"]] },
  { id: 'GUARD-9/runner-stops-restoring', suite: 'core',
    why: 'the runner stops putting the sources back after each mutant',
    catches: 'no longer restores after each mutant',
    patch: [['sim/mutants.mjs',
      '    } finally {\n      restore(); dirty = false\n    }',
      '    }']] },
  { id: 'GUARD-9/runner-stops-checking-the-tree', suite: 'core',
    why: 'the runner stops checking it left the tree clean',
    catches: 'no longer checks that it put the sources back',
    patch: [['sim/mutants.mjs', 'THE TREE IS STILL MUT' + 'ATED', 'some files may still be mutated']] },
  { id: 'GUARD-9/runner-abandons-on-interrupt', suite: 'core',
    why: 'the runner stops restoring the tree on Ctrl-C',
    // split for the same reason as the anchors: the guard greps this file for the signal
    // name, so leaving a whole copy here makes the mutant unable to fail.
    catches: 'no longer restores the tree on SIG' + 'INT',
    patch: [['sim/mutants.mjs', "  process.on('SIG" + "INT', () => { bail(); process.exit(130) })",
      "  process.on('SIGHUP', () => { bail(); process.exit(130) })"]] },

  // ---- BAL-16: a floor nobody can measure is not a floor -------------------------
  { id: 'BAL-16/buy-back-removed', suite: 'core',
    why: 'THE BUG: the Comp Kid back on its unmeasurable floor',
    catches: 'no psyche buy-back',
    patch: [['src/engine.ts', "quickFeet: true, dPsyche: 1, deed: 'strong',", "quickFeet: true, deed: 'strong',"]] },
  { id: 'BAL-16/buy-back-spreads', suite: 'core',
    why: 'the buy-back handed to a climber that did not need it',
    catches: 'this was a buy-back for one climber',
    patch: [['src/engine.ts', "    dContact: 1, settleMax: 0,", "    dContact: 1, settleMax: 0, dPsyche: 1,"]] },
  { id: 'BAL-16/bare-constant-cap', suite: 'core',
    why: 'a psyche cap goes back to the bare constant, so the dial stops applying there',
    catches: 'reads the bare constant again',
    patch: [['src/engine.ts', '      psyche: Math.min(psycheMax(s), s.psyche + PSYCHE_CAMP) })',
      '      psyche: Math.min(PSYCHE_MAX, s.psyche + PSYCHE_CAMP) })']] },
  { id: 'BAL-16/dial-ignored', suite: 'core',
    why: 'psycheMax stops reading the climber', catches: 'no longer reads the climber',
    patch: [['src/engine.ts', 'PSYCHE_MAX + (archOf(s).dPsyche ?? 0)', 'PSYCHE_MAX + 0']] },
  { id: 'BAL-16/floor-moved', suite: 'core',
    why: 'the 5% floor lowered to accommodate a climber — the BAL-9 failure',
    catches: 'the 5% floor has been moved',
    patch: [['sim/test.mjs', '    ok(lo > 5, `${E.ARCHETYPES[worst].name} completes only',
      '    ok(lo > 4, `${E.ARCHETYPES[worst].name} completes only']] },
  { id: 'BAL-16/margin-check-gone', suite: 'core',
    why: 'the guard stops checking its own margin is measurable',
    catches: 'no longer checks its own margin',
    patch: [['sim/test.mjs', '    ok(lo - 5 > 2 * se,', '    ok(lo - 5 > 0 * se,']] },
  { id: 'BAL-16/fine-pass-gone', suite: 'core',
    why: 'the guard stops resolving the lowest climber finely',
    catches: 'no longer resolves the lowest climber finely',
    patch: [['sim/test.mjs', 'PROJECTS=0 ARCH' + '_ONLY=${i} node sim/run.mjs arch ${FINE}',
      'PROJECTS=0 node sim/run.mjs arch ${FINE}']] },

  // ---- SKIRM-8: the good outcome gets a screen ------------------------------------
  { id: 'SKIRM-8/back-to-the-menu', suite: 'core',
    why: 'THE BUG: the walk-off goes straight to the guidebook again',
    catches: 'goes straight to the menu again',
    patch: [['src/engine.ts', "    phase: 'sessionEnd', result: 'walked' }", "    phase: 'menu', result: 'walked' }"]] },
  { id: 'SKIRM-8/unmarked', suite: 'core',
    why: 'the walk-off is unmarked, so its screen cannot tell what it was',
    catches: 'the walk-off is unmarked',
    patch: [['src/engine.ts', "    phase: 'sessionEnd', result: 'walked' }", "    phase: 'sessionEnd' }"]] },
  { id: 'SKIRM-8/reads-as-a-bail', suite: 'core',
    why: 'a walk-off marked as a bailed skirmish', catches: 'the walk-off is unmarked',
    patch: [['src/engine.ts', "    phase: 'sessionEnd', result: 'walked' }", "    phase: 'sessionEnd', result: 'bail' }"]] },
  { id: 'SKIRM-8/mode-comes-with-you', suite: 'core',
    why: 'the circuit mode is left set on the way out (MODE-1)',
    catches: 'the circuit mode came with you',
    patch: [['src/engine.ts', "  return { ...rec, circuit: false, skirmish: null, runDeck: [], log: [],",
      "  return { ...rec, skirmish: null, runDeck: [], log: [],"]] },
  { id: 'SKIRM-8/nothing-rendered', suite: 'core',
    why: 'the walk-off block is gated off, so the result is rendered nowhere',
    catches: 'the block with your score on it is not gated',
    patch: [['src/App.tsx', '        {walked ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--green)\' }}>',
      '        {false ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--green)\' }}>']] },
  { id: 'SKIRM-8/route-header-ungated', suite: 'core',
    why: 'the route header is shown on a walk-off, naming a route you were never on',
    catches: 'the route header is not gated',
    patch: [['src/App.tsx',
      '        {walked ? (\n          <div className="sub">the circuit · {zone.name.toLowerCase()}</div>\n        ) : (\n          <div className="sub">{spec.name}',
      '        {walked ? (\n          <div className="sub">the circuit</div>\n        ) : null}\n        {true ? (\n          <div className="sub">{spec.name}']] },
  { id: 'SKIRM-8/route-count-ungated', suite: 'core',
    why: 'the per-route burn and hold count shown on a walk-off (found by rendering it)',
    catches: 'is not about one route',
    patch: [['src/App.tsx', '        {walked ? null : (\n          <div style={{ fontSize:',
      '        {false ? null : (\n          <div style={{ fontSize:']] },
  { id: 'SKIRM-8/share-gone', suite: 'core',
    why: 'there is no way to paste what you did', catches: 'there is no way to paste',
    patch: [['src/App.tsx', 'circuitShare(st)', "'' /* gone */"]] },
  { id: 'SKIRM-8/best-claimed-wrongly', suite: 'core',
    why: 'a lesser circuit claims a personal best', catches: 'claims a personal best',
    patch: [['src/engine.ts', '  const best = s.circuitScore >= s.bestCircuit\n  const lines = [\n    \'Sandbagged · the circuit\',',
      '  const best = true\n  const lines = [\n    \'Sandbagged · the circuit\',']] },
  { id: 'SKIRM-8/plural-slip', suite: 'core',
    why: 'one line reads as "1 lines"', catches: 'one line reads as',
    patch: [['src/engine.ts', "`${s.circuitScore} line${s.circuitScore === 1 ? '' : 's'} ·", "`${s.circuitScore} lines ·"]] },

  // ---- SAVE-6: a save cannot claim an array longer than the game can make ---------
  { id: 'SAVE-6/history-unclamped', suite: 'core',
    why: 'THE BUG: history taken at whatever length the file claims',
    catches: 'against a cap of',
    patch: [['src/engine.ts', '      topRope: d.topRope ?? true, history: cap(d.history, HISTORY_MAX),',
      '      topRope: d.topRope ?? true, history: d.history ?? [],']] },
  { id: 'SAVE-6/owned-unclamped', suite: 'core',
    why: 'the collection taken at whatever length the file claims',
    catches: 'against a cap of',
    patch: [['src/engine.ts', '      owned: cap(d.owned, Object.keys(CARDS).length),',
      '      owned: d.owned ?? [],']] },
  { id: 'SAVE-6/run-arrays-unclamped', suite: 'core',
    why: 'the per-node run arrays taken at whatever length the file claims',
    catches: 'against a cap of',
    patch: [['src/engine.ts', '        trail: cap(d.run.trail, MAP_NODES)', '        trail: (d.run.trail ?? [])']] },
  { id: 'SAVE-6/clamp-becomes-a-wipe', suite: 'core',
    why: 'the clamp empties the field instead of keeping what fits',
    catches: 'was emptied rather than clamped',
    patch: [['src/engine.ts', '  Array.isArray(v) ? v.slice(0, n) : []', '  []']] },
  { id: 'SAVE-6/clamp-keeps-wrong-end', suite: 'core',
    why: 'the clamp keeps the tail instead of the head',
    catches: 'kept the wrong end of it',
    patch: [['src/engine.ts', '  Array.isArray(v) ? v.slice(0, n) : []', '  Array.isArray(v) ? v.slice(-n) : []']] },
  { id: 'SAVE-6/non-array-crashes', suite: 'core',
    why: 'a non-array where an array belongs takes the whole save down',
    catches: 'became unreadable',
    patch: [['src/engine.ts', '  Array.isArray(v) ? v.slice(0, n) : []', '  v.slice(0, n)']] },
  { id: 'SAVE-6/larder-grows-forever', suite: 'core',
    why: 'the larder appended to without a cap — the one that grows in normal play',
    catches: 'grows for ever in normal play',
    patch: [['src/engine.ts', '[...s.larder, rw.kit].slice(-LARDER_MAX)', '[...s.larder, rw.kit]']] },
  { id: 'SAVE-6/writer-cap-goes-bare', suite: 'core',
    why: "the writer's cap back to a literal the loader cannot know",
    catches: 'the first-ascent cap is a bare number again',
    patch: [['src/engine.ts', '.slice(0, ESTABLISHED_MAX),', '.slice(0, 40),']] },
  { id: 'SAVE-6/cap-is-nan', suite: 'core',
    why: 'a cap that is NaN, which silently caps nothing (the mistake this ticket made)',
    catches: 'not a number',
    patch: [['src/engine.ts', 'export const LARDER_MAX = KIT_MAX * 6', 'export const LARDER_MAX = KIT_MAX * undefined']] },

  // ---- ROUTE-15: the first lines in the book have a feature too --------------------
  { id: 'ROUTE-15/generated-switched-off', suite: 'core',
    why: 'THE BUG THIS TICKET SHIPPED: an empty candidate list read as "do not tag", so every grind line lost its feature',
    catches: 'named features, not one',
    patch: [['src/engine.ts', '  if (own || generated) {', '  if (own) {']] },
  { id: 'ROUTE-15/tag-removed', suite: 'core',
    why: 'one of the four earliest lines goes back to having no named feature',
    catches: 'lines carry a tagged feature, not the four earliest',
    patch: [['src/engine.ts', "sigTag: 'thegreen' }", '}']] },
  { id: 'ROUTE-15/feature-does-nothing', suite: 'core',
    why: 'a tagged feature loses its read and is a name on a hold again',
    catches: 'is just its base hold with a name on it',
    patch: [['src/engine.ts', "{ id: 'therail', local: true, name: 'The Rail', base: 'jug', read: 1,",
      "{ id: 'therail', local: true, name: 'The Rail', base: 'jug',"]] },
  { id: 'ROUTE-15/note-names-a-position', suite: 'core',
    why: "a feature's note goes back to naming where it is, on a line whose holds are shuffled",
    catches: 'names a position',
    patch: [['src/engine.ts', "    note: 'Big enough for two hands and a breather. Everybody uses it. Nobody rushes it.' },",
      "    note: 'You start from the floor, on your backside, the way everybody does.' },"]] },
  { id: 'ROUTE-15/tagged-carries-stats', suite: 'core',
    why: 'a tagged feature grows a dGrip — a number the tagger cannot apply, so it silently does nothing',
    catches: 'never applies',
    patch: [['src/engine.ts', "{ id: 'theflake', local: true, name: 'The Flake', base: 'crimp', read: 1,",
      "{ id: 'theflake', local: true, name: 'The Flake', base: 'crimp', read: 1, dGrip: 2,"]] },
  { id: 'ROUTE-15/tagger-rebuilds-hold', suite: 'core',
    why: 'the tagger replaces the hold instead of renaming it, which makes tagging band-active',
    catches: 'no longer spreads the existing hold',
    patch: [['src/engine.ts', 'if (at >= 0) { holds[at] = { ...holds[at], sig: id }; placed = true; break }',
      'if (at >= 0) { holds[at] = Object.assign({}, holds[at], { sig: id }); placed = true; break }']] },
  { id: 'ROUTE-15/tagger-rebuilds-fallback', suite: 'core',
    why: 'the OTHER write site rebuilds the hold — the first cut of this guard passed if either one still spread',
    catches: 'no longer spreads the existing hold',
    patch: [['src/engine.ts', 'if (at >= 0) holds[at] = { ...holds[at], sig: own }',
      'if (at >= 0) holds[at] = Object.assign({}, holds[at], { sig: own })']] },
  { id: 'ROUTE-15/pool-ignores-local', suite: 'core',
    why: 'the generated pool stops honouring `local`, so a feature about one place lands anywhere',
    catches: 'is in the generated pool',
    patch: [['src/engine.ts', 'SIGNATURES.filter(s => !s.ability && !s.local)',
      'SIGNATURES.filter(s => !s.ability)']] },
  { id: 'ROUTE-15/tagger-uses-run-rng', suite: 'core',
    why: 'the tagger draws from the run stream, so naming a feature shifts every roll after it',
    catches: 'draws from the run rng',
    patch: [['src/engine.ts', 'const ids = own ? [own] : sigRng.shuffle(GEN_SIG_IDS.slice())',
      'const ids = own ? [own] : rng.shuffle(GEN_SIG_IDS.slice())']] },
  { id: 'ROUTE-15/fallback-gone', suite: 'core',
    why: "a line's own feature is dropped when its preferred hold type did not roll",
    catches: 'named holds',
    patch: [['src/engine.ts', '    if (!placed && own) {', '    if (false && !placed && own) {']] },
  { id: 'ROUTE-15/local-gone', suite: 'core',
    why: 'a feature written about one specific place becomes taggable onto any generated line',
    catches: 'can land on a circuit line',
    patch: [['src/engine.ts', "{ id: 'thesitdown', local: true, name:", "{ id: 'thesitdown', name:"]] },
  { id: 'ROUTE-15/guidebook-blind', suite: 'core',
    why: 'the book only reads placed features, so four lines show as unnamed',
    catches: 'four lines read as unnamed',
    patch: [['src/App.tsx', "sigById(r.signature ?? r.sigTag ?? '')", "sigById(r.signature ?? '')"]] },
  { id: 'ROUTE-15/named-hold-guard-blind', suite: 'core',
    why: 'the named-hold guard forgets tagged features, so it stops covering four routes',
    catches: 'has a named hold it was not given',
    patch: [['sim/test-core.mjs', '    const owned = r.signature ?? r.sigTag ?? null',
      '    const owned = r.signature ?? null']] },

  // ---- NARR-15: the moments they were standing through in silence ------------------
  { id: 'NARR-15/resolve-reads-the-partner', suite: 'core',
    why: 'THE ONE NARR-14 REFUSED: the phase line goes back into resolve, where a partner can later be made to matter',
    catches: 'that is power, not narrative',
    patch: [['src/engine.ts', "    out = { ...out, phaseSeen: nowPh.name, log: [...out.log, `— ${nowPh.name.toUpperCase()} — ${nowPh.text}`] }",
      "    out = { ...out, phaseSeen: nowPh.name, log: [...out.log, `— ${nowPh.name.toUpperCase()} — ${nowPh.text}`, partnerSays(out, 'phase')] }"]] },
  { id: 'NARR-15/circuit-gets-a-death-line', suite: 'core',
    why: 'the circuit ending on skin is told it died — a trip line on a mode that is not a trip',
    catches: 'those are trip lines',
    patch: [['src/App.tsx', "partnerSays(st, st.circuit ? 'spent' : won ? 'top' : 'died')",
      "partnerSays(st, st.circuit ? 'died' : won ? 'top' : 'died')"]] },
  { id: 'NARR-15/trip-loses-its-word', suite: 'core',
    why: 'the trip ending loses the word NARR-14 put there',
    catches: 'the trip ends without a word',
    patch: [['src/App.tsx', "partnerSays(st, st.circuit ? 'spent' : won ? 'top' : 'died')",
      "partnerSays(st, 'spent')"]] },
  { id: 'NARR-15/walk-off-silent', suite: 'core',
    why: 'they push you to walk off for the whole circuit and then say nothing when you do',
    catches: 'you walk off on their advice and they say nothing',
    patch: [['src/App.tsx', '        {walked && partnerFor(st) ? (', '        {false && walked && partnerFor(st) ? (']] },
  { id: 'NARR-15/walk-off-reads-a-cleared-flag', suite: 'core',
    why: 'the walk-off block reads `circuit`, which is cleared on the way out, so it renders nothing',
    catches: 'which is cleared on the way out',
    patch: [['src/App.tsx', '        {walked && partnerFor(st) ? (', '        {st.circuit && partnerFor(st) ? (']] },
  { id: 'NARR-15/tutorial-banner-off', suite: 'kept',
    why: 'A HOLE THAT PREDATES THIS TICKET: the tutorial banner is switched off and its guard, unanchored, did not notice',
    catches: 'the tutorial banner is not gated on the tutorial route',
    patch: [['src/App.tsx', '      {spec.tutorial && tip ? (', '      {false && spec.tutorial && tip ? (']] },
  { id: 'NARR-15/nobody-on-the-walk-off', suite: 'core',
    why: 'FOUND BY A BROWSER: partnerFor reads a flag cleared on the way out, so the walk-off block renders nothing',
    catches: 'nobody is there on the walk-off screen',
    patch: [['src/engine.ts', "  if (!s.inRun && !s.circuit && s.result !== 'walked') return null",
      '  if (!s.inRun && !s.circuit) return null']] },
  { id: 'NARR-15/partner-on-the-guidebook', suite: 'core',
    why: 'the walk-off exemption is widened until somebody stands on a screen with no run happening',
    catches: 'a partner is standing on a screen where no run is happening',
    patch: [['src/engine.ts', "  if (!s.inRun && !s.circuit && s.result !== 'walked') return null",
      "  if (!s.inRun && !s.circuit && s.result === 'never') return null"]] },
  { id: 'NARR-15/fall-line-on-a-walk-off', suite: 'core',
    why: 'the send/fall line goes back to rendering on a walk-off — "Feet." on an ending where nothing fell',
    catches: 'nothing was sent and nothing fell',
    patch: [['src/App.tsx', '        {!walked && partnerFor(st) ? (', '        {partnerFor(st) ? (']] },
  { id: 'NARR-15/claim-silent', suite: 'core',
    why: 'the FA screen goes back to saying "nobody to ask" with somebody standing there',
    catches: 'somebody is standing there',
    patch: [['src/App.tsx', "            {partnerSays(st, 'claim')}</div>) : null}",
      '            </div>) : null}']] },
  { id: 'NARR-15/menu-fa-grows-a-partner', suite: 'core',
    why: 'the solo menu FA stops saying you went on your own, so somebody appears out of nowhere',
    catches: 'so a partner appears out of nowhere',
    patch: [['src/App.tsx', 'skirmish: route, inRun: false, tier: 0,\n      runDeck: loadoutDeck(st.loadouts[st.arch])',
      'skirmish: route, tier: 0,\n      runDeck: loadoutDeck(st.loadouts[st.arch])']] },
  { id: 'NARR-15/curse-silent', suite: 'core',
    why: 'taking a curse on purpose stops being something they have a view on',
    catches: 'no view on taking a curse',
    patch: [['src/App.tsx', '        {two && partnerFor(st) ? (', '        {false && two && partnerFor(st) ? (']] },
  { id: 'NARR-15/phase-silent', suite: 'core',
    why: 'a route changes under you and nobody remarks on it',
    catches: 'nobody remarks on it',
    patch: [['src/App.tsx', "          {partnerSays(st, 'phase')}</div> : null}</div> : null}",
      '          </div> : null}</div> : null}']] },
  { id: 'NARR-15/phase-with-nobody-there', suite: 'core',
    why: 'the phase line renders on a skirmish, where nobody came out with you, as an empty block',
    catches: 'renders with nobody there',
    patch: [['src/App.tsx', "        {partnerFor(st) ? <div style={{ marginTop: 3, color: 'var(--dim)' }}\n          role=",
      "        {true ? <div style={{ marginTop: 3, color: 'var(--dim)' }}\n          role="]] },
  { id: 'NARR-15/a-moment-is-a-stub', suite: 'core',
    why: 'two partners share a line, so who came out with you stops mattering at that moment',
    catches: 'so who came out with you does not matter',
    patch: [['src/engine.ts', "      claim: '\"Call it what the rock is.\" He means it literally, and it is not bad advice.',",
      "      claim: '\"That is soft for the grade.\" She has climbed it zero times and is completely certain.',"]] },
  { id: 'NARR-15/a-moment-is-recycled', suite: 'core',
    why: 'a new moment is filled with a line the partner already says somewhere else',
    catches: 'a line they already had somewhere else',
    patch: [['src/engine.ts', "      walked: '\"Finally.\" He has been standing by something he wants you to look at for about an hour.',",
      "      walked: '\"Did you see the quartz band? No. You would not have.\" He is not disappointed in you.',"]] },
  { id: 'NARR-15/partner-moves-the-grade', suite: 'core',
    why: 'the partner nudges the FA grade — text becoming power, which is the whole rule',
    catches: 'the number on this screen is yours',
    patch: [['src/App.tsx', '    const suggest = () => {',
      '    if (partnerFor(st)) setClaim({ ...c, grade: c.grade })\n    const suggest = () => {']] },

  // ---- A11Y-9: a screen reader hears the turn, not the last line of it -------------
  { id: 'A11Y-9/back-to-one-line', suite: 'core',
    why: 'THE BUG: the live region back to the last log line, which is about a fifth of a turn',
    catches: 'back to announcing one line',
    patch: [['src/App.tsx', '<div className="vis-hidden" role="status" aria-live="polite">{spoken}</div>',
      `<div className="vis-hidden" role="status" aria-live="polite">
        {st.log.length ? st.log[st.log.length - 1] : ''}</div>`]] },
  { id: 'A11Y-9/announces-a-sample', suite: 'core',
    why: 'the effect stops sending the lines that were added and goes back to a sample',
    catches: 'so it is back to a sample',
    patch: [['src/App.tsx', 'setSpoken(st.log.slice(logSeen.current).join(\' \'))',
      'setSpoken(st.log.slice(-1).join(\' \'))']] },
  { id: 'A11Y-9/replays-the-old-burn', suite: 'core',
    why: 'a new burn empties the log and the whole previous burn is read out from the start',
    catches: 'this would replay the old one',
    patch: [['src/App.tsx', '    if (n < logSeen.current) { logSeen.current = n; setSpoken(\'\'); return }',
      '']] },
  { id: 'A11Y-9/region-reads-nothing', suite: 'core',
    why: 'the live region stops reading what the effect computed',
    catches: 'does not read what the effect computed',
    patch: [['src/App.tsx', '<div className="vis-hidden" role="status" aria-live="polite">{spoken}</div>',
      '<div className="vis-hidden" role="status" aria-live="polite">{\'\'}</div>']] },
  { id: 'A11Y-9/sequence-silent', suite: 'core',
    why: 'a sequence starts mid-climb and nothing is announced',
    catches: 'a sequence starts and nothing is announced',
    patch: [['src/App.tsx', '        <div className="spot" role="status" aria-live="polite" style={{ borderLeftColor: \'var(--green)\' }}>\n          <b style={{ color: \'var(--green)\' }}>\n            {seqById(st.seq.id)!.name.toUpperCase()}',
      '        <div className="spot" style={{ borderLeftColor: \'var(--green)\' }}>\n          <b style={{ color: \'var(--green)\' }}>\n            {seqById(st.seq.id)!.name.toUpperCase()}']] },
  { id: 'A11Y-9/phase-approach-silent', suite: 'core',
    why: 'the phase gets closer and nothing is announced',
    catches: 'the phase gets closer and nothing is announced',
    patch: [['src/App.tsx', '          <div className="spot" role="status" aria-live="polite" style={{ borderLeftColor: \'var(--tan)\' }}>\n            <b style={{ color: \'var(--tan)\' }}>\n              {nx.away} HOLD',
      '          <div className="spot" style={{ borderLeftColor: \'var(--tan)\' }}>\n            <b style={{ color: \'var(--tan)\' }}>\n              {nx.away} HOLD']] },
  { id: 'A11Y-9/curse-silent-to-a-reader', suite: 'core',
    why: 'arming a curse changes the screen under you and announces nothing',
    catches: 'arming a curse announces nothing',
    patch: [['src/App.tsx', `          <div className="spot" role="status" aria-live="polite"
            style={{ borderLeftColor: 'var(--tan)', marginTop: 6 }}>`,
      "          <div className=\"spot\" style={{ borderLeftColor: 'var(--tan)', marginTop: 6 }}>"]] },
  { id: 'A11Y-9/phase-banner-doubles', suite: 'core',
    why: 'the phase banner announces too, so the phase is read out twice — once from the log, once here',
    catches: 'which the log region already read out',
    patch: [['src/App.tsx', "      {phase ? <div className=\"spot\" style={{ borderLeftColor: 'var(--ink)' }}>",
      "      {phase ? <div className=\"spot\" role=\"status\" style={{ borderLeftColor: 'var(--ink)' }}>"]] },
  { id: 'A11Y-9/partner-clause-silent', suite: 'core',
    why: "the partner's phase clause loses its live region — the one line on that banner the log never carries",
    catches: 'the one line here the log never carries',
    patch: [['src/App.tsx', "        {partnerFor(st) ? <div style={{ marginTop: 3, color: 'var(--dim)' }}\n          role=\"status\" aria-live=\"polite\">",
      "        {partnerFor(st) ? <div style={{ marginTop: 3, color: 'var(--dim)' }}>"]] },

  // ---- DEV-7: an update never takes the player off the screen they are on ---------
  { id: 'DEV-7/gate-back-to-mid-climb', suite: 'core',
    why: 'THE BUG AS REPORTED: the reload gate back to mid-climb, so an update throws the player off any other screen',
    catches: 'the reload gate is not the splash any more',
    patch: [['src/App.tsx', '.__SB_BUSY__ = booted', ".__SB_BUSY__ = st.phase === 'climb' || st.phase === 'burnEnd'"]] },
  { id: 'DEV-7/gate-on-the-wrong-dep', suite: 'core',
    why: 'the flag is published on a dependency that is not the splash, so it goes stale',
    catches: 'a dependency that is not the splash',
    patch: [['src/App.tsx', '  }, [booted])\n  const weather = WEATHER[st.weather]',
      '  }, [st.phase])\n  const weather = WEATHER[st.weather]']] },
  { id: 'DEV-7/reload-ungated', suite: 'core',
    why: 'the reload stops asking whether it is safe',
    catches: 'not gated on the flag at all',
    patch: [['scripts/build-html.mjs', '`if(!window.__SB_BUSY__){location.reload()}});`',
      '`location.reload()});`']] },
  { id: 'DEV-7/poll-returns', suite: 'core',
    why: 'the retired poll comes back, spinning for ever on a flag that can never change',
    catches: 'polls a flag that can no longer change',
    patch: [['scripts/build-html.mjs', '`if(!window.__SB_BUSY__){location.reload()}});`',
      '`var t=setInterval(function(){if(!window.__SB_BUSY__){clearInterval(t);location.reload()}},4000);`+\n  `if(!window.__SB_BUSY__){clearInterval(t);location.reload()}});`']] },
  { id: 'DEV-7/first-install-bounces', suite: 'core',
    why: 'the prior-controller check goes, so a first install bounces the page',
    catches: 'a first install bounces the page',
    patch: [['scripts/build-html.mjs', '`if(!had||done)return;done=true;`', '`if(done)return;done=true;`']] },
  { id: 'DEV-7/loader-restores-phase', suite: 'core',
    why: 'somebody "fixes" the bounce by restoring phase instead, which is the SAVE-4 hole',
    catches: 'which is how a reload reopens the post',
    patch: [['src/engine.ts', '      runs: d.runs ?? 0, falls: d.falls ?? 0,',
      '      phase: d.phase, runs: d.runs ?? 0, falls: d.falls ?? 0,']] },

  // ---- ART-4: the day comes out as a picture ---------------------------------------
  { id: 'ART-4/download-link-returns', suite: 'core',
    why: 'THE ROUTE THIS TICKET RULED OUT: a download link, which iOS and an installed PWA drop on the floor',
    catches: 'a download link is back',
    patch: [['src/App.tsx', '      setCardUrl(URL.createObjectURL(blob))',
      "      const a = document.createElement('a'); a.download = 'x.png'; a.click()\n      setCardUrl(URL.createObjectURL(blob))"]] },
  { id: 'ART-4/share-without-asking', suite: 'core',
    why: 'the share sheet is handed a file without asking whether it takes files',
    catches: 'without asking whether it takes files',
    patch: [['src/App.tsx', 'if (nav.canShare?.({ files: [file] })) {', 'if (nav.share) {']] },
  { id: 'ART-4/file-never-shared', suite: 'core',
    why: 'the share sheet opens with nothing in it',
    catches: 'the file is never handed to the share sheet',
    patch: [['src/App.tsx', 'await navigator.share({ files: [file] })', 'await navigator.share({ title: '
      + "'Sandbagged' })"]] },
  { id: 'ART-4/fallback-says-nothing', suite: 'core',
    why: 'the fallback shows a picture and never says how to save it',
    catches: 'which is the whole fallback',
    patch: [['src/App.tsx', 'Press and hold the picture to save it.', 'Here it is.']] },
  { id: 'ART-4/sheet-on-the-wrong-screen', suite: 'core',
    why: 'THE BUG A BROWSER FOUND: the picture renders in a component that returned earlier, so it is drawn and never seen',
    catches: 'no way to appear on the screen that makes it',
    patch: [['src/App.tsx', '      {cardUrl ? (\n        <div className="sheet"',
      '      {false && cardUrl ? (\n        <div className="sheet"']] },
  { id: 'ART-4/url-never-revoked', suite: 'core',
    why: 'every canvas a session ever drew is held for the life of the page',
    catches: 'the last picture is not released',
    patch: [['src/App.tsx', '  useEffect(() => () => { if (cardUrl) URL.revokeObjectURL(cardUrl) }, [cardUrl])',
      '  useEffect(() => () => {}, [cardUrl])']] },
  { id: 'ART-4/two-renderings-drift', suite: 'core',
    why: 'the paste shows a different grid from the picture',
    catches: 'show different grids',
    patch: [['src/engine.ts', "  const c = shareCard(s)\n  const lines = [\n    `Sandbagged \u00b7 ${c.day}`,",
      "  const c = { ...shareCard(s) }\n  c.grid = '\u25aa'.repeat(1)\n  const lines = [\n    `Sandbagged \u00b7 ${c.day}`,"]] },
  { id: 'ART-4/paste-recomputes-the-grid', suite: 'core',
    why: 'the paste goes back to building the grid itself, which is the copy that drifts',
    catches: 'computes its own grid again',
    patch: [['src/engine.ts', "  const c = shareCard(s)\n  const lines = [",
      "  const spec2 = specOf(s)\n  const h2 = Math.max(0, Math.min(s.cleared, spec2.clear))\n"
      + "  const c = { ...shareCard(s), grid: '\u25aa'.repeat(h2) + '\u25ab'.repeat(Math.max(0, spec2.clear - h2)) }\n  const lines = ["]] },
  { id: 'ART-4/grid-loses-a-hold', suite: 'core',
    why: 'the grid stops being one mark per hold on the route',
    catches: 'not one mark per hold',
    patch: [['src/engine.ts', "    grid: '\u25aa'.repeat(holds) + '\u25ab'.repeat(Math.max(0, spec.clear - holds)),",
      "    grid: '\u25aa'.repeat(holds) + '\u25ab'.repeat(Math.max(0, spec.clear - holds - 1)),"]] },
  { id: 'ART-4/filled-marks-lie', suite: 'core',
    why: 'the filled marks stop being the holds you actually got',
    catches: 'not the holds you got',
    patch: [['src/engine.ts', '    holds, clear: spec.clear,', '    holds: Math.max(0, holds - 1), clear: spec.clear,']] },
  { id: 'ART-4/share-touches-the-rng', suite: 'core',
    why: 'the projection draws from the rng, so looking at your result could change a run',
    catches: 'the share draws from the rng',
    patch: [['src/engine.ts', '    score: s.dailyScore,', '    score: s.dailyScore + new RNG(1).int(0),']] },

  // ---- BAL-13: act 1 is frictionless, and no dial fixes that -----------------------
  { id: 'BAL-13/diagnostic-gone', suite: 'core',
    why: 'the acts diagnostic is removed, so the finding cannot be re-measured',
    catches: 'the acts diagnostic is gone',
    patch: [['sim/run.mjs', "if (mode === 'acts') {", "if (mode === 'acts-disabled') {"]] },
  { id: 'BAL-13/trough-not-tracked', suite: 'core',
    why: 'the probe goes back to the act-boundary value, which is post-camp and says "you can recover" instead of "you were under pressure"',
    catches: 'the skin trough is not actually being tracked',
    patch: [['sim/run.mjs', '      if (s.skin < lowSkin) lowSkin = s.skin',
      '      if (false) lowSkin = s.skin']] },
  { id: 'BAL-13/probe-touches-the-policy', suite: 'core',
    why: 'the measurement probe reaches into the run loop, so it measures itself',
    catches: 'measures itself',
    patch: [['sim/run.mjs', '      if (s.skin < lowSkin) lowSkin = s.skin\n      if (s.psyche < lowPsyche) lowPsyche = s.psyche',
      '      if (s.skin < lowSkin) lowSkin = s.skin\n      s = E.startBurn(s, rng)\n      if (s.psyche < lowPsyche) lowPsyche = s.psyche']] },
  { id: 'BAL-13/act-1-grows-teeth', suite: 'slow',
    why: 'THE THING THE PIN IS FOR: act 1 is given a flat approach cost, which is one of the five levers already known to blow the climber spread',
    catches: 'under skin pressure',
    patch: [['src/engine.ts', 'export function startBurn(s: GameState, rng: RNG): GameState {\n  const spec = specOf(s)',
      'export function startBurn(s: GameState, rng: RNG): GameState {\n'
      + '  if (s.inRun && s.burn === 1 && s.act === 0) s = { ...s, skin: Math.max(1, s.skin - 2) }\n'
      + '  const spec = specOf(s)']] },

  // ---- SHIP-3: the site is packageable, and the claims about it are true -----------
  { id: 'SHIP-3/maskable-relabelled', suite: 'core',
    why: 'THE THING THAT LOOKS FINE: the plain icon relabelled as maskable, which a round launcher mask then crops',
    catches: 'the next build relabels the plain one',
    patch: [['scripts/build-html.mjs', "{ src: './icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },",
      "{ src: './icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },"]] },
  { id: 'SHIP-3/nojekyll-dropped', suite: 'core',
    why: 'docs/.nojekyll goes, so Pages runs Jekyll, Jekyll drops dot-directories, and assetlinks 404s with no symptom but a URL bar',
    catches: 'the build no longer emits .nojekyll',
    patch: [['scripts/build-html.mjs', "writeFileSync(join('docs', '.nojekyll'), '')",
      "// writeFileSync(join('docs', '.nojekyll'), '')"]] },
  { id: 'SHIP-3/placeholder-fingerprint', suite: 'core',
    why: 'the build stops refusing a malformed fingerprint, so a stub assetlinks can ship and fail verification silently',
    catches: 'no longer refuses a malformed fingerprint',
    patch: [['scripts/build-html.mjs', "  throw new Error('SANDBAGGED_SHA256 is set but is not 32 colon-separated hex pairs — refusing '",
      "  console.warn('bad fingerprint, writing it anyway ('"]] },
  { id: 'SHIP-3/privacy-gone', suite: 'core',
    why: 'the privacy policy stops being emitted, and Play requires the URL',
    catches: 'no longer emits the privacy policy',
    patch: [['scripts/build-html.mjs', "writeFileSync(join('docs', 'privacy.html'), privacy)",
      "void privacy"]] },
  { id: 'SHIP-3/tracker-added', suite: 'core',
    why: 'a tracker reaches the bundle while the privacy policy tells Play there is none',
    catches: 'tells Play there is no tracking',
    patch: [['docs/index.html', '<link rel="manifest" href="./manifest.webmanifest">',
      '<script>/* google-analytics */</script><link rel="manifest" href="./manifest.webmanifest">']] },
  { id: 'SHIP-3/external-host', suite: 'core',
    why: 'the build starts referencing a host the privacy policy says it never talks to',
    catches: 'the privacy policy says it talks to nothing',
    patch: [['docs/index.html', '<link rel="apple-touch-icon" href="./icon-192.png">',
      '<link rel="preconnect" href="https://cdn.example.com"><link rel="apple-touch-icon" href="./icon-192.png">']] },
  { id: 'SHIP-3/config-disagrees', suite: 'core',
    why: 'the Bubblewrap config and the web manifest name different maskable icons, so the app ships the wrong one',
    catches: 'name different maskable icons',
    patch: [['ship/twa-manifest.json', '"maskableIconUrl": "https://rcjlabs.github.io/sandbagged/icon-maskable-512.png"',
      '"maskableIconUrl": "https://rcjlabs.github.io/sandbagged/icon-512.png"']] },
  { id: 'SHIP-3/shell-injected-twice', suite: 'core',
    why: 'the build stops refusing a repeat injection, which doubles the PWA head and registers the service worker twice',
    catches: 'no longer refuses to inject the shell twice',
    patch: [['scripts/build-html.mjs', "if (html.includes('rel=\"manifest\"') || html.includes('serviceWorker.register')) {",
      'if (false) {']] },
  { id: 'SHIP-3/keystore-committable', suite: 'core',
    why: 'THE EXPENSIVE ONE: the signing key stops being gitignored while the checklist still says it is',
    catches: 'is not an active gitignore rule',
    patch: [['.gitignore', 'ship/*.keystore', '# ship/*.keystore']] },

  // ---- SKIRM-9: the circuit ending wears its own furniture -------------------------
  { id: 'SKIRM-9/trip-furniture-returns', suite: 'core',
    why: 'THE BUG: CIRCUIT OVER goes back to naming an act and a stage on a mode that has neither',
    catches: 'no longer tells a circuit from a trip',
    patch: [['src/App.tsx', '        <div className="sub">{st.circuit\n          ? <>the circuit',
      '        <div className="sub">{false\n          ? <>the circuit']] },
  { id: 'SKIRM-9/zone-dropped', suite: 'core',
    why: 'the circuit ending stops naming its zone, so it has no furniture of its own at all',
    catches: 'does not name its zone',
    patch: [['src/App.tsx', 'the circuit · {circuitZone(st.circuitScore).name.toLowerCase()} · deck',
      'the circuit · deck']] },
  { id: 'SKIRM-9/trip-loses-its-own', suite: 'core',
    why: 'the fix overreaches and the TRIP ending loses the act and stage it is supposed to show',
    catches: 'the trip ending lost the act and stage',
    patch: [['src/App.tsx', ': <>{ACT_NAMES[st.act]} · stage {st.tier + 1} · deck {st.runDeck.length}</>}',
      ': <>deck {st.runDeck.length}</>}']] },

  // ---- PERF-2: the bundle is measured, and the size is pinned ----------------------
  { id: 'PERF-2/throttle-dropped', suite: 'core',
    why: 'the perf script stops throttling, so it measures this machine rather than a phone and the answer stops meaning anything',
    catches: 'no longer throttles both measurements',
    patch: [['scripts/perf.mjs', "if (rate > 1) await cdp.send('Emulation.setCPUThrottlingRate', { rate })   // throttle AFTER setup",
      '// throttle AFTER setup']] },
  { id: 'PERF-2/rates-narrowed', suite: 'core',
    why: 'the sweep stops covering the rates the answer was measured at',
    catches: 'no longer sweeps the throttle rates',
    patch: [['scripts/perf.mjs', 'for (const rate of [1, 4, 6]) {\n  const runs = []', 'for (const rate of [1]) {\n  const runs = []']] },
  { id: 'PERF-2/script-unhooked', suite: 'core',
    why: 'npm run perf is removed, so nobody re-measures before re-asking the question',
    catches: 'npm run perf is gone',
    patch: [['package.json', '"perf": "node scripts/perf.mjs"', '"perf-disabled": "node scripts/perf.mjs"']] },

  // ---- A11Y-10: a screen change announces, on every screen -------------------------
  { id: 'A11Y-10/focus-not-moved', suite: 'core',
    why: 'THE GAP THIS FIXED: nothing moves focus on a phase change, so a screen reader is told nothing at all',
    catches: 'no longer moves focus',
    patch: [['src/App.tsx', '    h.focus({ preventScroll: true })', '    void h']] },
  { id: 'A11Y-10/heading-not-focusable', suite: 'core',
    why: 'the heading is not made focusable, so focus() on a div silently does nothing',
    catches: 'focus() is a no-op on a div',
    patch: [['src/App.tsx', '    h.tabIndex = -1', '    void 0']] },
  { id: 'A11Y-10/wrong-deps', suite: 'core',
    why: 'the effect stops firing on a phase change, so only the first screen ever announces',
    catches: 'no longer fires on a phase change',
    patch: [['src/App.tsx', '  }, [st.phase, booted])', '  }, [booted])']] },
  { id: 'A11Y-10/announced-twice', suite: 'core',
    why: 'a mount-time live region comes back alongside the heading focus, so the block is read out twice',
    catches: 'so it is read twice',
    patch: [['src/App.tsx', '        {mate ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--tan)\' }}>',
      '        {mate ? (\n          <div className="spot" style={{ borderLeftColor: \'var(--tan)\' }} role="status">']] },

  // ---- SAVE-7: a new expedition carries everything that is yours --------------------
  { id: 'SAVE-7/journal-lost', suite: 'core',
    why: 'THE BUG: the journal stops being carried, so the only meta-progression resets on every expedition and the autosave writes the empty array',
    catches: 'the only meta-progression resets',
    patch: [['src/engine.ts', '    journal: s.journal, dailyTried: s.dailyTried,', '    dailyTried: s.dailyTried,']] },
  { id: 'SAVE-7/daily-gate-lost', suite: 'core',
    why: "SAVE-4's anti-farm gate stops being carried, so starting a trip makes today's daily available again",
    catches: 'dailyTried does not survive starting an expedition',
    patch: [['src/engine.ts', '    journal: s.journal, dailyTried: s.dailyTried,', '    journal: s.journal,']] },
  { id: 'SAVE-7/diff-stops-diffing', suite: 'core',
    why: 'a new account field is added to the save and not carried — the next instance of this bug, which the guard exists to catch',
    catches: 'that is SAVE-7 again',
    patch: [['src/engine.ts', '      sends: s.sends, wins: s.wins, journal: s.journal, loadout: s.loadout,',
      '      sends: s.sends, wins: s.wins, journal: s.journal, loadout: s.loadout, trophies: s.trophies,']] },
  { id: 'SAVE-7/exemption-goes-stale', suite: 'core',
    why: 'a field stays exempt on the grounds that newRun takes it, after newRun stops taking it',
    catches: 'it no longer does',
    patch: [['src/App.tsx', 'newRun(pickSeed(), st.loadouts[st.arch], st.style, st.arch, st.mutators)',
      'newRun(pickSeed(), st.loadouts[st.arch], st.style, st.arch, [])']] },

  // ---- NARR-16: every page he wrote is worth the same on the wall -------------------
  { id: 'NARR-16/wall-counts-six', suite: 'slow',
    why: 'THE BUG: the wall goes back to counting only pages 1-6, so the eight NARR-11 added are worth nothing on it again',
    catches: 'NARR-16 again',
    patch: [['src/engine.ts', '  return UNREAD_MAX - Math.ceil(UNREAD_MAX * held / FINDABLE)',
      '  return UNREAD_MAX - Math.min(UNREAD_MAX, journal.filter(p => p <= 6).length)']] },
  { id: 'NARR-16/wall-hand-rolls-again', suite: 'core',
    why: 'the wall stops asking the one function and works its own blindness out, which is the shape that let the two drift apart',
    catches: 'instead of asking unreadGrip',
    patch: [['src/engine.ts', '  const unread = spec.finale ? BLIND_HOLD + unreadGrip(s.journal) : 0',
      '  const unread = spec.finale ? Math.max(0, JOURNAL.length - 1 - s.journal.filter(p => p <= 6).length) : 0']] },
  { id: 'NARR-16/card-promises-more', suite: 'core',
    why: 'the map card works its own blindness out again, so it can tell you the route is readable while the route charges you',
    catches: 'so it can disagree with the route',
    patch: [['src/App.tsx', '                  const blind = unreadGrip(st.journal)',
      '                  const blind = Math.max(0, 6 - held)']] },
  { id: 'NARR-16/first-page-worthless', suite: 'core',
    why: 'the ceiling goes back to a round, so the first page he wrote buys nothing and finding one early reads as a dud',
    catches: 'the whole reason for the ceiling',
    patch: [['src/engine.ts', '  return UNREAD_MAX - Math.ceil(UNREAD_MAX * held / FINDABLE)',
      '  return UNREAD_MAX - Math.round(UNREAD_MAX * held / FINDABLE)']] },
  { id: 'NARR-16/flat-cost-unnamed', suite: 'core',
    why: "NARR-11's eight grip goes back to being an unexplained number folded into an expression",
    catches: 'is no longer named',
    patch: [['src/engine.ts', '  const unread = spec.finale ? BLIND_HOLD + unreadGrip(s.journal) : 0',
      '  const unread = spec.finale ? 8 + unreadGrip(s.journal) : 0']] },
  { id: 'NARR-16/summit-page-counts', suite: 'slow',
    why: 'the summit page counts as beta you carried up, so topping out once makes the next finale easier for a page you read afterwards',
    catches: 'you read it AFTER',
    patch: [['src/engine.ts', '  const held = Math.min(journal.filter(p => p !== 7).length, FINDABLE)',
      '  const held = Math.min(journal.length, FINDABLE)']] },
]

/* ---- the runner -------------------------------------------------------------- */

const SUITES = {
  core: 'node sim/test-core.mjs',
  kept: 'node sim/test.mjs',
  slow: 'node sim/test.mjs slow',
}

/** Every file any mutant touches. */
export const touched = () => [...new Set(MUTANTS.flatMap(m => m.patch.map(p => p[0])))]

/** Apply one mutant's patches to a working copy of the sources. Throws if an anchor is
    not present exactly once, which is the whole point — a mutant whose anchor has moved
    is a mutant that tests nothing, so it must be loud rather than skipped. */
export function applyPatch(mutant, read) {
  const out = new Map()
  for (const [file, from, to] of mutant.patch) {
    const src = out.get(file) ?? read(file)
    const n = src.split(from).length - 1
    if (n !== 1) {
      throw new Error(`${mutant.id}: its anchor in ${file} matches ${n} times, not once — the mutant is dead:\n    ${from.split('\n')[0]}`)
    }
    out.set(file, src.replace(from, to))
  }
  return out
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const arg = process.argv[2]
  const wantSlow = arg === 'slow'
  const only = arg && !wantSlow ? arg : null
  const chosen = MUTANTS.filter(m =>
    (only ? m.id.startsWith(only) : true) && (m.suite === 'slow' ? wantSlow || only : true))

  const files = touched()
  const snapshot = new Map(files.map(f => [f, readFileSync(f, 'utf8')]))
  const restore = () => { for (const [f, src] of snapshot) writeFileSync(f, src) }
  let dirty = false
  const bail = () => { if (dirty) { restore(); dirty = false } }
  process.on('SIGINT', () => { bail(); process.exit(130) })
  process.on('uncaughtException', e => { bail(); console.error(e); process.exit(1) })

  console.log(`\n  ${chosen.length} mutant${chosen.length === 1 ? '' : 's'}` +
    `${only ? ` matching ${only}` : ''}${wantSlow ? ' (including the ledger ones)' : ''}\n`)
  const missed = []
  let ticket = ''
  for (const m of chosen) {
    const t = m.id.split('/')[0]
    if (t !== ticket) { console.log(`  ${t}`); ticket = t }
    let caught = false, note = ''
    try {
      for (const [f, src] of applyPatch(m, f2 => snapshot.get(f2))) { writeFileSync(f, src); dirty = true }
      let out = ''
      try { out = execSync(SUITES[m.suite], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }) }
      catch (e) { out = `${e.stdout ?? ''}${e.stderr ?? ''}` }
      caught = out.includes(m.catches)
      if (!caught) note = /✗/.test(out) ? 'something else failed instead' : 'the suite passed'
    } catch (e) {
      note = e.message
    } finally {
      restore(); dirty = false
    }
    console.log(`    ${caught ? '✓' : '✗'} ${m.why}`)
    if (!caught) { console.log(`        expected to see: ${m.catches}${note ? ` — ${note}` : ''}`); missed.push(m) }
  }

  // the sources must be exactly as we found them
  const changed = files.filter(f => readFileSync(f, 'utf8') !== snapshot.get(f))
  if (changed.length) {
    console.error(`\n  THE TREE IS STILL MUTATED: ${changed.join(', ')} — put them back before doing anything else\n`)
    process.exit(2)
  }
  console.log(`\n  ${chosen.length - missed.length}/${chosen.length} caught` +
    `${wantSlow || only ? '' : `  (run \`node sim/mutants.mjs slow\` for the ${MUTANTS.filter(m => m.suite === 'slow').length} ledger one${MUTANTS.filter(m => m.suite === 'slow').length === 1 ? '' : 's'})`}\n`)
  process.exit(missed.length ? 1 : 0)
}
